prometheus:
  url: http://kube-prometheus-stack-prometheus.default.svc
  port: 9090
  path: ""
rules:
  default: false
  custom:
    - seriesQuery: '{__name__=~"^http_server_requests_seconds_.*"}'
      resources:
        overrides:
          namespace: { resource: "namespace" }
          pod: { resource: "pod" }
      name:
        matches: "^http_server_requests_seconds_count(.*)"
        as: "http_server_requests_seconds_count_sum"
      metricsQuery: sum(rate(http_server_requests_seconds_count{<<.LabelMatchers>>, uri=~"/forecast.*"}[1m])) by (<<.GroupBy>>)
nodeSelector:
  node: app