prometheus:
  url: http://kube-prometheus-stack-prometheus.default.svc
  port: 9090
  path: ""
rules:
  default: false
  custom:
    - seriesQuery: 'http_server_requests_seconds_count'
      resources:
        overrides:
          namespace: { resource: "namespace" }
          pod: { resource: "pod" }
      name:
        matches: "http_server_requests_seconds_count"
        as: "http_server_requests_seconds_count_sum"
      metricsQuery: sum(irate(<<.Series>>{<<.LabelMatchers>>,uri=~"/forecast.*"}[1m]))
nodeSelector:
  node: app