apiVersion: v1
kind: Service
metadata:
  name: weather-service
  labels:
    app: weather-app
spec:
  type: ClusterIP
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082